name: plouf

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: make it uni
        run: |
          brew update || true
          brew fetch --bottle-tag=big_sur --deps mpfr
          brew fetch --bottle-tag=arm64_big_sur --deps mpfr
