name: plouf

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: make it uni
        run: |
          brew update || true
          mkdir deps-amd64
          cd deps-amd64
          tar xf "`brew fetch --bottle-tag=big_sur gmp        | sed -ne 's/^Downloaded to: //p'`"
          tar xf "`brew fetch --bottle-tag=big_sur mpfr       | sed -ne 's/^Downloaded to: //p'`"
          cd ..
          mkdir deps-arm64
          cd deps-arm64
          tar xf "`brew fetch --bottle-tag=arm64_big_sur gmp  | sed -ne 's/^Downloaded to: //p'`"
          tar xf "`brew fetch --bottle-tag=arm64_big_sur mpfr | sed -ne 's/^Downloaded to: //p'`"
          cd ..
          ls deps-*/*/*/lib
          mkdir -p deps-uni/lib
          for A in gmp mpfr; do
            for X in deps-amd64/$A/*/lib/lib*; do
              Y=`basename $X`
              lipo -create $X deps-arm64/$A/*/lib/$Y -output deps-uni/lib/$Y
            done
          done
          ls deps-uni/lib
          file deps-uni/lib/*
